default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: ansible_testing_development
test:
  <<: *default
  database: ansible_testing_test
production:
  <<: *default
  url: <%= ENV['ANSIBLE_TESTING_DATABASE_URL'] %>
  database: <%= ENV['ANSIBLE_TESTING_DATABASE_NAME'] %>
